<?php

/*
 * TIPOS DE CAMPOS
 */
define('CAMPO_TIPO_TEXTO_LIVRE', 	1);
define('CAMPO_TIPO_NUMERO_INTEIRO', 2);

/*
 * TIPOS DE WIDGETS
 */
define('WIDGET_TIPO_TABELA', 1);
define('WIDGET_TIPO_BUTTON_POPUP_INSERTER', 2);

/*
 * LAYOUTS DE MASHUPS
 */
define('MASHUP_LAYOUT_FULLPAGE', 1);

/*
 * STYLES PARA MASHUPS
 */
define('MASHUP_STYLE_1', 1);
define('MASHUP_STYLE_2', 2);